# R for travis: see documentation at
# https://docs.travis-ci.com/user/languages/r
# Also see the wiki:
# https://github.com/craigcitro/r-travis/wiki

language: r
sudo: false
cache: packages

after_failure:
  - ./travis-tool.sh dump_logs

after_script:
  - ./travis-tool.sh dump_logs_by_extension "timings"
  - ./travis-tool.sh dump_sysinfo

notifications:
  email:
    on_success: sbalcome@mdic.org
    on_failure: sbalcome@mdic.org
env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual --no-resave-data"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - R_CHECK_TIME="TRUE"
    - R_CHECK_TESTS="TRUE"
    - _R_CHECK_TIMINGS_="0"
